name: Deploy Frontend to Namecheap via RSYNC

on:
  push:
    branches:
      - main  # Your production branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code 📂
        uses: actions/checkout@v3

      - name: Set up Bun 🟢
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies 📦
        run: bun install

      - name: Build React app 🏗️
        run: bun run build
        env:
          CI: false  # This prevents the build from treating warnings as errors
          
      - name: Install rsync 🛰️
        run: sudo apt-get install -y rsync sshpass
          
      - name: Create .htaccess file for SPA routing 📄
        run: |
          echo "Options -MultiViews
          RewriteEngine On
          RewriteCond %{REQUEST_FILENAME} !-f
          RewriteRule ^ index.html [QSA,L]" > dist/.htaccess

      - name: Deploy with rsync and password 🚀
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          # Disable strict host key checking for this deployment
          mkdir -p ~/.ssh
          echo "StrictHostKeyChecking no" >> ~/.ssh/config
          echo "UserKnownHostsFile=/dev/null" >> ~/.ssh/config
          
          # Deploy using rsync with explicit password authentication
          export SSHPASS="$SSH_PASSWORD"
          sshpass -e rsync -avz --delete \
            -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p 21098" \
            ./dist/ \
            ironobty@192.64.117.206:~/inkcopilot.com/
          
          # Debug info if rsync fails
          if [ $? -ne 0 ]; then
            echo "Rsync failed. Trying to debug the connection..."
            sshpass -e ssh -o StrictHostKeyChecking=no -p 21098 ironobty@192.64.117.206 echo "SSH connection successful"
          fi
            
      - name: Verify deployment 🔍
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          export SSHPASS="$SSH_PASSWORD"
          sshpass -e ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p 21098 ironobty@192.64.117.206 'cd ~/inkcopilot.com && ls -la && echo "Frontend deployment completed successfully!"'
